"""JSON/XML field extraction operations for derived columns.

Log columns that hold a whole nested document in one cell are the norm in
DFIR data — EVTX `EventData`, cloud audit `requestParameters`, EDR
telemetry blobs. The grid can only show that as one long unreadable
string, and you can't sort, filter or group by something buried inside it.
These operations lift one field out into a real column.

They ride the same registry and the same machinery as the timestamp
operations in `timeparse.py` (see its `register_op` docstring — it is
explicitly the seam for this) rather than growing a parallel one, because
what a derived column needs is identical either way: a per-row `parse`,
a params schema, a backfill into the `drv_<id>` sidecar, and a definition
that sessions can carry and recompute. The only thing that differs is what
comes out, so these ops carry `derived_kind: "text"` and
`family: "extract"` — the latter is what keeps them out of the "Add
datetime column" picker, which is a different question the analyst is
asking.

Stdlib only, and imports nothing from the app except the registry itself.

**Paths are the analyst's addressing scheme, so they have to survive being
written down.** They go into a column definition, a session file and the
UI, so both syntaxes are text, both round-trip through parse/format, and
both are generated by clicking a node in the detail pane rather than being
typed from scratch:

    JSON   $.user.name    items[0].id    ["odd.key"].value
    XML    Event/System/EventID    Provider@Name    Data[2]

XML safety: `<!DOCTYPE ...>` is refused outright rather than parsed.
ElementTree expands internal entities (verified — a billion-laughs payload
parses rather than raising), and cell values here are untrusted evidence
that a plugin author, a suspect or a broken exporter wrote. No log field
this feature targets carries a DOCTYPE, so refusing one costs nothing real
and removes the entire entity-expansion question. There is no network
fetch of external entities either way — ElementTree never resolves them.
"""

from __future__ import annotations

import json
import re
import xml.etree.ElementTree as ET
from typing import Any, Iterator

import timeparse

# A cell big enough to be a denial-of-service against the backfill rather
# than a log field. 8 MB is far past any real EventData blob and still
# parses in well under the time one BATCH of rows takes.
MAX_DOC_BYTES = 8 * 1024 * 1024

# How deep path enumeration walks, and how many distinct paths it will
# report. Both are guards against a pathological document (a deeply
# recursive structure, or a map keyed by GUID with 50,000 entries) turning
# "show me what's in here" into a hang.
MAX_WALK_DEPTH = 24
MAX_PATHS = 400

_DOCTYPE_RE = re.compile(r"<!DOCTYPE", re.IGNORECASE)


def _leaf_text(value: Any) -> str:
    """A JSON value at the point extraction stops -> TEXT.

    Same convention as store.py's `_json_leaf_text` (all values are TEXT;
    an object or array is JSON-stringified whole rather than dropped or
    half-flattened), duplicated rather than imported because this module
    stays free of app imports. A JSON `null` becomes an empty cell, not a
    missing one — the field was there and it was null, which is different
    from the field not being present at all (see `_extract_json`).
    """
    if value is None:
        return ""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (dict, list)):
        return json.dumps(value, ensure_ascii=False)
    return str(value)


# ------------------------------------------------------------- JSON paths

_JSON_TOKEN_RE = re.compile(
    r"""
    \.\s*(?P<dotkey>[^.\[\]"']+)      # .key
    | \[\s*(?P<index>-?\d+)\s*\]      # [0]
    | \[\s*"(?P<dq>(?:\\.|[^"\\])*)"\s*\]   # ["key"]
    | \[\s*'(?P<sq>(?:\\.|[^'\\])*)'\s*\]   # ['key']
    | (?P<barekey>[^.\[\]"']+)        # leading key with no dot
    """,
    re.VERBOSE,
)


def parse_json_path(text: str) -> list:
    """`$.a.b[0]` / `a.b` / `["odd.key"].v` -> ['a', 'b', 0].

    Leading `$` is optional (SQLite's json_extract spells it, most people
    don't). Bracket-quoting is the escape hatch for keys containing a dot
    or a bracket, which dot notation alone can't address — a real shape in
    cloud audit logs, where keys are often URLs or ARNs.
    """
    s = str(text or "").strip()
    if not s:
        raise ValueError("A field path is required")
    if s.startswith("$"):
        s = s[1:]
    out: list = []
    pos = 0
    while pos < len(s):
        if s[pos].isspace():
            pos += 1
            continue
        m = _JSON_TOKEN_RE.match(s, pos)
        if not m or m.end() == pos:
            raise ValueError(f"Can't read the field path at {s[pos:pos + 12]!r}")
        if m.group("index") is not None:
            out.append(int(m.group("index")))
        else:
            key = m.group("dotkey") or m.group("barekey")
            if key is None:
                raw = m.group("dq") if m.group("dq") is not None else m.group("sq")
                key = re.sub(r"\\(.)", r"\1", raw)
            out.append(key.strip())
        pos = m.end()
    if not out:
        raise ValueError(f"Can't read the field path {text!r}")
    return out


def format_json_path(segments: list) -> str:
    """The inverse of parse_json_path, and the form shown in the UI. Keys
    that dot notation can't express unambiguously come back bracket-quoted,
    so format(parse(x)) is always re-parseable."""
    out = "$"
    for seg in segments:
        if isinstance(seg, int):
            out += f"[{seg}]"
        elif re.fullmatch(r"[^.\[\]\"']+", str(seg)):
            out += f".{seg}"
        else:
            out += '["' + str(seg).replace("\\", "\\\\").replace('"', '\\"') + '"]'
    return out


def load_json(value: Any) -> Any:
    """A cell -> a parsed JSON document, or None if it isn't one."""
    if value is None:
        return None
    s = str(value).strip()
    if not s or s[0] not in "{[" or len(s) > MAX_DOC_BYTES:
        return None
    try:
        return json.loads(s)
    except (ValueError, RecursionError):
        return None


_MISSING = object()


def _walk_json(doc: Any, segments: list) -> Any:
    cur = doc
    for seg in segments:
        if isinstance(seg, int):
            if not isinstance(cur, list):
                return _MISSING
            try:
                cur = cur[seg]
            except IndexError:
                return _MISSING
        else:
            if not isinstance(cur, dict) or seg not in cur:
                return _MISSING
            cur = cur[seg]
    return cur


def json_leaf_paths(doc: Any) -> list[tuple[list, Any]]:
    """Every addressable leaf in a document, as (segments, value).

    Objects are walked; so are arrays, but only far enough to be useful —
    an array of scalars is a leaf in its own right (a list of IPs is one
    column, not N), while an array of objects is indexed into, because
    that's the shape where the interesting fields live (`Data[0].Name`).
    That asymmetry is deliberate and matches store.py's `_flatten_json`
    reasoning about varying array lengths: index-expanding a scalar list
    would make the offered column set vary row to row for no gain.
    """
    out: list[tuple[list, Any]] = []

    def walk(value: Any, path: list, depth: int) -> None:
        if len(out) >= MAX_PATHS or depth > MAX_WALK_DEPTH:
            return
        if isinstance(value, dict):
            if not value:
                out.append((path, value))
                return
            for k, v in value.items():
                walk(v, path + [str(k)], depth + 1)
        elif isinstance(value, list):
            if value and all(isinstance(x, (dict, list)) for x in value):
                for i, v in enumerate(value):
                    walk(v, path + [i], depth + 1)
            else:
                out.append((path, value))
        else:
            out.append((path, value))

    walk(doc, [], 0)
    return out


def _extract_json(value: Any, params: dict, state: dict) -> str | None:
    """One row. None means "this row has no such field" — which the
    derived-column machinery counts and can filter to, and which is a
    genuinely different answer from "the field is there and it's empty".
    A JSON `null` is the latter, and comes back as ''."""
    doc = load_json(value)
    if doc is None:
        return None
    segments = state.get("segments")
    if segments is None:
        segments = state["segments"] = parse_json_path(params["path"])
    found = _walk_json(doc, segments)
    if found is _MISSING:
        return None
    return _leaf_text(found)


# -------------------------------------------------------------- XML paths

def _split_steps(s: str) -> list[str]:
    """`a/b[@N='x/y']/c` -> ['a', "b[@N='x/y']", 'c'] — a plain split would
    cut the predicate in half, and predicate values are analyst data
    (file paths, URLs) that routinely contain slashes."""
    out, buf, depth = [], [], 0
    for ch in s:
        if ch == "[":
            depth += 1
        elif ch == "]":
            depth = max(0, depth - 1)
        if ch == "/" and depth == 0:
            out.append("".join(buf))
            buf = []
        else:
            buf.append(ch)
    out.append("".join(buf))
    return out


def _trailing_at(s: str) -> int | None:
    """Index of the `@` that selects an attribute — the last one at bracket
    depth zero — or None if the path selects an element's text."""
    depth = 0
    found = None
    for i, ch in enumerate(s):
        if ch == "[":
            depth += 1
        elif ch == "]":
            depth = max(0, depth - 1)
        elif ch == "@" and depth == 0:
            found = i
    return found


_XML_STEP_RE = re.compile(
    r"""^(?P<tag>[^\[\]@/]+)
    (?:\[
        (?: (?P<index>\d+)
          | @(?P<pattr>[\w:.-]+)\s*=\s*(?P<quote>['"])(?P<pval>[^'"]*)(?P=quote)
        )
    \])?$""",
    re.VERBOSE,
)


def parse_xml_path(text: str) -> tuple[list[tuple[str, Any]], str | None]:
    """`Event/System/EventID` -> ([('Event', 0), ('System', 0),
    ('EventID', 0)], None); a trailing `@Name` is returned separately as
    the attribute to read instead of the element's text.

    A step selects among same-named siblings either positionally (`[n]`,
    0-based) or by attribute (`[@Name='TargetUserName']`, the XPath
    spelling). The predicate form exists because of Windows event logs,
    where the entire payload is `<Data Name="TargetUserName">jacson</Data>`
    repeated — addressing that by position gives you a column called
    "Data[4]" whose meaning shifts between event IDs, while addressing it
    by name gives you a column called "TargetUserName" that means the same
    thing in every row that has one. `discover_paths` prefers the
    predicate form for exactly that reason.

    Namespaces are matched on the local name (see `_local`), because a log
    field's fully-qualified `{http://...}Data` is noise the analyst never
    wants to type or read.
    """
    s = str(text or "").strip()
    if not s:
        raise ValueError("A field path is required")
    attr = None
    # Only a trailing `@attr` selects an attribute. An `@` inside brackets
    # belongs to a predicate (`Data[@Name='X']`) and must not be split on —
    # partitioning at the first `@` turned that path into the element
    # `Event/EventData/Data[` and lost the rest.
    at = _trailing_at(s)
    if at is not None:
        attr = s[at + 1:].strip()
        s = s[:at].strip()
        if not attr:
            raise ValueError("Expected an attribute name after '@'")
    steps: list[tuple[str, Any]] = []
    for raw in _split_steps(s):
        raw = raw.strip()
        if not raw:
            continue
        m = _XML_STEP_RE.match(raw)
        if not m:
            raise ValueError(f"Can't read the element path at {raw!r}")
        if m.group("pattr"):
            sel: Any = (m.group("pattr"), m.group("pval"))
        else:
            sel = int(m.group("index") or 0)
        steps.append((m.group("tag").strip(), sel))
    if not steps and attr is None:
        raise ValueError(f"Can't read the element path {text!r}")
    return steps, attr


def _format_step(tag: str, sel: Any) -> str:
    if isinstance(sel, tuple):
        return f"{tag}[@{sel[0]}='{sel[1]}']"
    return tag if sel == 0 else f"{tag}[{sel}]"


def format_xml_path(steps: list[tuple[str, Any]], attr: str | None = None) -> str:
    out = "/".join(_format_step(t, sel) for t, sel in steps)
    return f"{out}@{attr}" if attr else out


def _local(tag: str) -> str:
    """`{http://schemas...}Data` -> `Data`."""
    return tag.rsplit("}", 1)[-1] if "}" in tag else tag


def load_xml(value: Any) -> "ET.Element | None":
    """A cell -> a parsed element, or None if it isn't usable XML.

    Two tolerances that matter on real data: a `<?xml?>` prolog is fine,
    and a *fragment* with several top-level elements (common when a field
    holds a slice of a larger document) is retried inside a synthetic root
    rather than rejected. A DOCTYPE is refused — see the module docstring.
    """
    if value is None:
        return None
    s = str(value).strip()
    if not s or not s.startswith("<") or len(s) > MAX_DOC_BYTES:
        return None
    if _DOCTYPE_RE.search(s):
        return None
    try:
        return ET.fromstring(s)
    except ET.ParseError:
        pass
    try:
        # Wrapping re-parses the prolog as content, so drop it first.
        body = re.sub(r"^<\?xml[^>]*\?>", "", s).strip()
        return ET.fromstring(f"<winnow-fragment>{body}</winnow-fragment>")
    except ET.ParseError:
        return None


def _xml_root_steps(root: ET.Element) -> list[str]:
    """The synthetic fragment wrapper is an implementation detail — paths
    are written against what was actually in the cell."""
    return [] if root.tag == "winnow-fragment" else [_local(root.tag)]


def _attr_value(node: ET.Element, name: str) -> str | None:
    for k, v in node.attrib.items():
        if _local(k) == name:
            return v
    return None


def _xml_find(root: ET.Element, steps: list[tuple[str, Any]]) -> "ET.Element | None":
    if not steps:
        return root
    # A path written against a real document starts at its root element;
    # one written against a fragment starts at the first of its children.
    if root.tag != "winnow-fragment":
        tag, sel = steps[0]
        if _local(root.tag) != tag or sel != 0:
            return None
        cur, rest = root, steps[1:]
    else:
        cur, rest = root, steps
    for tag, sel in rest:
        matches = [c for c in cur if _local(c.tag) == tag]
        if isinstance(sel, tuple):
            attr, want = sel
            matches = [c for c in matches if _attr_value(c, attr) == want]
            if not matches:
                return None
            cur = matches[0]
        else:
            if sel >= len(matches):
                return None
            cur = matches[sel]
    return cur


# Attribute names that identify a repeated element rather than describing
# it. Checked case-insensitively and in order — `Name` first because that
# is what Windows event logs use, which is most of the XML this feature
# will ever meet.
_ID_ATTRS = ("name", "key", "id")


def _sibling_selectors(kids: list[ET.Element]) -> list[Any]:
    """How to address each child among its same-named siblings: positional
    normally, but by attribute when a repeated element carries one that
    tells its instances apart.

    This is what turns an EVTX `EventData` block into columns called
    `TargetUserName` and `LogonType` instead of `Data[4]` and `Data[8]` —
    positional paths through a repeated element are not stable across
    event IDs, so a column built on one means something different from row
    to row. Only used when the attribute is present on *every* one of the
    same-named siblings and its values are distinct, since otherwise the
    predicate wouldn't identify a single element either.
    """
    groups: dict[str, list[int]] = {}
    for i, c in enumerate(kids):
        groups.setdefault(_local(c.tag), []).append(i)

    sel: list[Any] = [0] * len(kids)
    for tag, idxs in groups.items():
        chosen = None
        if len(idxs) > 1:
            for want in _ID_ATTRS:
                vals = [_attr_ci(kids[i], want) for i in idxs]
                named = [_real_attr_name(kids[i], want) for i in idxs]
                if all(v is not None for v in vals) and len(set(vals)) == len(vals):
                    chosen = (named[0], vals)
                    break
        if chosen:
            attr, vals = chosen
            for slot, i in enumerate(idxs):
                sel[i] = (attr, vals[slot])
        else:
            for slot, i in enumerate(idxs):
                sel[i] = slot
    return sel


def _attr_ci(node: ET.Element, lowered: str) -> str | None:
    """Attribute lookup by lowercased local name — used only to *probe* for
    an identifying attribute. The path that comes out records the
    attribute's real spelling (see _real_attr_name), and matching a written
    path back against a document stays case-sensitive, as XML requires."""
    for k, v in node.attrib.items():
        if _local(k).lower() == lowered:
            return v
    return None


def _real_attr_name(node: ET.Element, lowered: str) -> str:
    """The attribute's own spelling, so a path round-trips against the
    document rather than against our lowercased probe."""
    for k in node.attrib:
        if _local(k).lower() == lowered:
            return _local(k)
    return lowered


def xml_leaf_paths(root: ET.Element) -> list[tuple[str, str]]:
    """Every addressable value in a document, as (path, sample text) —
    element texts and attributes both, since which of the two an EVTX-style
    `<Data Name="TargetUserName">jacson</Data>` puts the useful part in
    depends entirely on who wrote the exporter."""
    out: list[tuple[str, str]] = []
    base = _xml_root_steps(root)

    def walk(node: ET.Element, steps: list[tuple[str, Any]], depth: int) -> None:
        if len(out) >= MAX_PATHS or depth > MAX_WALK_DEPTH:
            return
        here = format_xml_path(steps)
        # The attribute that selected this element restates the predicate
        # (`Data[@Name='LogonType']@Name` is always 'LogonType'), so it's
        # noise in the picker rather than a field worth a column.
        selector = steps[-1][1] if steps and isinstance(steps[-1][1], tuple) else None
        for name, val in node.attrib.items():
            if selector and _local(name) == selector[0] and val == selector[1]:
                continue
            out.append((f"{here}@{_local(name)}" if here else f"@{_local(name)}", val))
        kids = list(node)
        if not kids:
            text = (node.text or "").strip()
            if here:
                out.append((here, text))
            return
        for child, sel in zip(kids, _sibling_selectors(kids)):
            walk(child, steps + [(_local(child.tag), sel)], depth + 1)

    walk(root, [(t, 0) for t in base], 0)
    return out


def _extract_xml(value: Any, params: dict, state: dict) -> str | None:
    root = load_xml(value)
    if root is None:
        return None
    parsed = state.get("xpath")
    if parsed is None:
        parsed = state["xpath"] = parse_xml_path(params["path"])
    steps, attr = parsed
    node = _xml_find(root, steps)
    if node is None:
        return None
    if attr:
        for name, val in node.attrib.items():
            if _local(name) == attr:
                return val
        return None
    return (node.text or "").strip()


# ------------------------------------------------------------- operations

_PATH_PARAM_JSON = {
    "name": "path", "label": "Field path", "type": "text", "required": True,
    "help": "e.g. $.user.name or items[0].id — click a field in the detail pane to fill this in.",
}
_PATH_PARAM_XML = {
    "name": "path", "label": "Element path", "type": "text", "required": True,
    "help": "e.g. Event/System/EventID, or Data[2]@Name for an attribute — "
            "click a field in the detail pane to fill this in.",
}

def _validate_json_params(params: dict) -> None:
    parse_json_path(params.get("path", ""))


def _validate_xml_params(params: dict) -> None:
    parse_xml_path(params.get("path", ""))


timeparse.register_op({
    "id": "json_field",
    "label": "JSON field",
    "description": "Pull one field out of a JSON document stored in this column.",
    "params": [_PATH_PARAM_JSON],
    "parse": _extract_json,
    "validate": _validate_json_params,
    "value_type": "text",
    "derived_kind": "text",
    "family": "extract",
    "stateful": True,  # the parsed path is cached in `state` across the batch
    "hidden_from_detect": True,
})

timeparse.register_op({
    "id": "xml_field",
    "label": "XML field",
    "description": "Pull one element or attribute out of an XML document stored in this column.",
    "params": [_PATH_PARAM_XML],
    "parse": _extract_xml,
    "validate": _validate_xml_params,
    "value_type": "text",
    "derived_kind": "text",
    "family": "extract",
    "stateful": True,
    "hidden_from_detect": True,
})


# --------------------------------------------------------------- discovery

def sniff_kind(values: Iterator | list) -> str | None:
    """'json' | 'xml' | None for a column, from a sample of its values.
    Majority wins; a column has to be mostly one shape before the UI offers
    to take it apart."""
    vals = [str(v) for v in values if v is not None and str(v).strip()]
    if not vals:
        return None
    js = sum(1 for v in vals if load_json(v) is not None)
    if js * 2 > len(vals):
        return "json"
    xm = sum(1 for v in vals if load_xml(v) is not None)
    if xm * 2 > len(vals):
        return "xml"
    return None


def discover_paths(values: list, kind: str) -> list[dict]:
    """Every field found across a sample, with how many of the sampled rows
    had it and one example value.

    Coverage is the number that makes this list usable: a path present in
    3 of 200 rows is a different proposition from one present in 200, and
    ordering by it puts the columns worth making at the top. Sorted by
    coverage, then by path, so the same sample always produces the same
    order — the analyst is ticking checkboxes against this list.
    """
    counts: dict[str, int] = {}
    nonempty: dict[str, int] = {}
    samples: dict[str, str] = {}
    labels: dict[str, str] = {}
    seen_rows = 0
    for raw in values:
        if raw is None or not str(raw).strip():
            continue
        if kind == "json":
            doc = load_json(raw)
            if doc is None:
                continue
            found = [(format_json_path(p), _leaf_text(v)) for p, v in json_leaf_paths(doc)]
        else:
            root = load_xml(raw)
            if root is None:
                continue
            found = xml_leaf_paths(root)
        seen_rows += 1
        for path, sample in dict(found).items():
            counts[path] = counts.get(path, 0) + 1
            if sample != "":
                nonempty[path] = nonempty.get(path, 0) + 1
            if path not in samples and sample:
                samples[path] = sample[:200]
            labels.setdefault(path, suggest_name(path, kind))
    # `count` is "the field is there"; `nonempty` is "there's something in
    # it". They come apart for a container element whose value lives in its
    # attributes — `<TimeCreated SystemTime="..."/>` is present in every row
    # and empty in every row, and a column of blanks is not what ticking a
    # 100%-coverage field should get you. The caller uses nonempty to decide
    # what to preselect; both are reported rather than folded together, so
    # "present but always empty" stays visible instead of vanishing.
    out = [
        {"path": p, "count": n, "coverage": (n / seen_rows) if seen_rows else 0.0,
         "nonempty": nonempty.get(p, 0),
         "sample": samples.get(p, ""), "suggested_name": labels[p]}
        for p, n in counts.items()
    ]
    # Fields with something in them first, then by coverage — the ticking
    # order should match the "is this worth a column" order.
    out.sort(key=lambda r: (-r["nonempty"], -r["count"], r["path"]))
    return out[:MAX_PATHS]


def suggest_name(path: str, kind: str) -> str:
    """A column name from a path — the last meaningful component, which is
    what the analyst would have typed. Collisions with existing columns are
    the caller's problem (store.add_derived_column already refuses them and
    the batch path disambiguates)."""
    s = str(path)
    # `Data[@Name='TargetUserName']` names itself — that predicate value is
    # a better column name than anything its tag or position could give.
    pred = re.search(r"\[@[\w:.-]+='([^']*)'\]$", s)
    if pred and pred.group(1).strip():
        return pred.group(1).strip()
    if "@" in s and not s.rstrip().endswith("]"):
        head, _, attr = s.rpartition("@")
        tail = head.rstrip("/").split("/")[-1] if head.strip("/") else ""
        tail = re.sub(r"\[[^\]]*\]$", "", tail)
        return f"{tail} {attr}".strip() if tail else attr
    if kind == "json":
        try:
            segs = parse_json_path(s)
        except ValueError:
            return s
        for seg in reversed(segs):
            if not isinstance(seg, int):
                return str(seg)
        return s.lstrip("$.")
    last = s.rstrip("/").split("/")[-1]
    return re.sub(r"\[\d+\]$", "", last) or s
